version: '3'
services:
  monicahq:
    build:
      context: .
      dockerfile: Dockerfile.dev
    links:
      - mysql
    ports:
      - 8080:80
    env_file: .env.dev
    volumes:
    - ./:/var/www/monica

  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=sekret_root_password
      - MYSQL_DATABASE=monica
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
